# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc6914bb9731352b06743c1a81d3ef12ad9660a523cd301a1a63221abd520a6f67799dc6571af219bdd89fa169c7acfb0ee8bdb1f5271604eebdff6f12bc8214

test:
  secret_key_base: 32f13253ae6a519b0bd108bb45bb637a995b16ce3c83650b1df671e1ca1192af460a66ff6575a3ac46b863324b777617adc21925b4aec3abf9c44cfa12b5cdb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
